# Generated by Django 2.2 on 2019-04-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Класс Жилья')),
            ],
            options={
                'verbose_name': 'Класс Жилья',
                'verbose_name_plural': 'Классы Жилья',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Срок сдачи')),
            ],
            options={
                'verbose_name': 'Срок сдачи',
                'verbose_name_plural': 'Сроки сдачи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Застройщик')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Район')),
                ('subname', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Сокращённое')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Материал дома')),
            ],
            options={
                'verbose_name': 'Материал дома',
                'verbose_name_plural': 'Материалы дома',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentМethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JkObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Жилой Комплекс')),
                ('image', models.ImageField(blank=True, upload_to='jkobject_images/')),
                ('class_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_building', to='jk_objects.ClassBuilding', verbose_name='Класс Жилья')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='jk_objects.Developer', verbose_name='Застройщик')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='jk_objects.District', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Жилой Комплекс',
                'verbose_name_plural': 'Жилые Комплексы',
                'ordering': ['name'],
            },
        ),
    ]
