# Generated by Django 2.2 on 2019-04-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlinebuilding',
            options={'verbose_name': 'Срок сдачи', 'verbose_name_plural': 'Сроки сдачи'},
        ),
    ]
