# Generated by Django 2.2 on 2019-04-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0003_auto_20190406_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jkobject',
            name='district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='district', to='jk_objects.District', verbose_name='Район'),
        ),
    ]
