# Generated by Django 2.2 on 2019-04-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0008_auto_20190406_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Отделка квартиры')),
            ],
            options={
                'verbose_name': 'Отделка квартиры',
                'verbose_name_plural': 'Отделки квартиры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseOfObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Адрес')),
                ('floors', models.CharField(db_index=True, max_length=150, verbose_name='Этажность')),
                ('bank', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bank', to='jk_objects.Bank', verbose_name='Банки')),
                ('deadline', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deadline', to='jk_objects.DeadlineBuilding', verbose_name='Срок сдачи')),
                ('finishing_flat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='finishingflat', to='jk_objects.FinishingFlat', verbose_name='Отделка квартиры')),
                ('house_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='housematerial', to='jk_objects.HouseMaterial', verbose_name='Материал дома')),
                ('payment_method', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='paymentmethod', to='jk_objects.PaymentМethod', verbose_name='Способы оплаты')),
            ],
            options={
                'verbose_name': 'Дом объекта',
                'verbose_name_plural': 'Дома объекта',
                'ordering': ['address'],
            },
        ),
    ]
