# Generated by Django 2.2 on 2019-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0010_auto_20190406_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseofobject',
            name='floors',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Этажность'),
        ),
    ]
