# Generated by Django 2.2 on 2019-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0011_auto_20190407_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='jkobject',
            name='address',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, unique=True, verbose_name='Адрес'),
        ),
    ]
