# Generated by Django 2.2 on 2019-04-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0013_auto_20190407_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseofobject',
            old_name='bank',
            new_name='banks',
        ),
    ]
