# Generated by Django 2.2 on 2019-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jk_objects', '0014_auto_20190408_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseofobject',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='houseofobject',
            name='floors',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Этажность'),
        ),
    ]
