# Generated by Django 2.2 on 2019-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_crudajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateField(null=True)),
                ('author', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('book_type', models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('E-book', 'E-book')], max_length=120)),
            ],
        ),
    ]
